fix(ThemeColor): set the themeColor by the --easy-table-theme-color css variable
The use of v-bind is causing js crash like:
TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.